# l10n.yaml
arb-dir: lib/application/l10n
template-arb-file: intl_en.arb
synthetic-package: false
output-dir: lib/application/l10n
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [ en ]